package system

import "time"

// processingSimulationDelay stands in for the real extraction -> chunking ->
// embedding pipeline (ai package, future work). It lets the upload -> ready
// lifecycle the frontend already renders be exercised end to end today.
const processingSimulationDelay = 3 * time.Second

// CreateMaterial records a newly uploaded file as "processing" and starts
// its (simulated) processing in the background. id is generated by the
// caller (apis.handleUploadMaterial) because the on-disk storage path must
// be chosen before the store record can be created.
func (s *Store) CreateMaterial(id, filename, materialType, uploadedByID, uploadedByName, destinationPath, storagePath string) *Material {
	s.mu.Lock()
	m := &Material{
		ID:              id,
		Filename:        filename,
		Type:            materialType,
		UploadedByID:    uploadedByID,
		UploadedByName:  uploadedByName,
		UploadedAt:      timeNow(),
		DestinationPath: destinationPath,
		Status:          MaterialProcessing,
		StoragePath:     storagePath,
	}
	s.materials[m.ID] = m
	s.mu.Unlock()

	s.startProcessing(m.ID)
	return m
}

func (s *Store) startProcessing(id string) {
	go func() {
		time.Sleep(processingSimulationDelay)
		s.mu.Lock()
		defer s.mu.Unlock()
		if m, ok := s.materials[id]; ok {
			m.Status = MaterialReady
			m.RAGAvailable = true
		}
	}()
}

// ListMaterials returns all materials, most recently uploaded first.
func (s *Store) ListMaterials() []*Material {
	s.mu.RLock()
	defer s.mu.RUnlock()

	out := make([]*Material, 0, len(s.materials))
	for _, m := range s.materials {
		out = append(out, m)
	}
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j].UploadedAt.After(out[j-1].UploadedAt); j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}

// GetMaterial looks up a material by ID.
func (s *Store) GetMaterial(id string) (*Material, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	m, ok := s.materials[id]
	if !ok {
		return nil, ErrNotFound
	}
	return m, nil
}

// UpdateMaterialDestination changes where a material's content is routed.
// Callers must validate the path first (see storage.ValidateDestinationPath).
func (s *Store) UpdateMaterialDestination(id, destinationPath string) (*Material, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	m, ok := s.materials[id]
	if !ok {
		return nil, ErrNotFound
	}
	m.DestinationPath = destinationPath
	return m, nil
}

// DeleteMaterial removes a material's record and returns it so the caller
// can clean up its on-disk file.
func (s *Store) DeleteMaterial(id string) (*Material, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	m, ok := s.materials[id]
	if !ok {
		return nil, ErrNotFound
	}
	delete(s.materials, id)
	return m, nil
}

// ReprocessMaterial resets a material to "processing" and restarts the
// (simulated) pipeline.
func (s *Store) ReprocessMaterial(id string) (*Material, error) {
	s.mu.Lock()
	m, ok := s.materials[id]
	if !ok {
		s.mu.Unlock()
		return nil, ErrNotFound
	}
	m.Status = MaterialProcessing
	m.RAGAvailable = false
	s.mu.Unlock()

	s.startProcessing(id)
	return m, nil
}
