package system

import (
	"context"
	"strconv"
	"time"
)

// materialProcessingTimeout bounds how long extraction, chunking, and
// embedding may take for a single material before it's marked failed.
const materialProcessingTimeout = 2 * time.Minute

// CreateMaterial records a newly uploaded file as "processing" and starts
// its processing in the background. id is generated by the caller
// (apis.handleUploadMaterial) because the on-disk storage path must be
// chosen before the store record can be created.
func (s *Store) CreateMaterial(id, filename, materialType, uploadedByID, uploadedByName, destinationPath, storagePath string) *Material {
	return s.CreateMaterialFromSource(id, filename, materialType, uploadedByID, uploadedByName, destinationPath, string(MaterialSourceUpload), filename, storagePath)
}

// CreateMaterialFromSource records material from any supported source and
// starts its processing in the background.
func (s *Store) CreateMaterialFromSource(id, filename, materialType, uploadedByID, uploadedByName, destinationPath, sourceType, sourceLocation, storagePath string) *Material {
	s.mu.Lock()
	m := &Material{
		ID:              id,
		Filename:        filename,
		Type:            materialType,
		SourceType:      MaterialSourceType(sourceType),
		SourceLocation:  sourceLocation,
		UploadedByID:    uploadedByID,
		UploadedByName:  uploadedByName,
		UploadedAt:      timeNow(),
		DestinationPath: destinationPath,
		Status:          MaterialProcessing,
		StoragePath:     storagePath,
	}
	s.materials[m.ID] = m
	s.mu.Unlock()

	s.startProcessing(m.ID)
	return m
}

// startProcessing runs the configured MaterialProcessor in the background
// and records the outcome (chunks + ready, or failed) on the material.
func (s *Store) startProcessing(id string) {
	s.mu.RLock()
	processor := s.processor
	s.mu.RUnlock()

	go func() {
		if processor == nil {
			s.mu.Lock()
			if m, ok := s.materials[id]; ok {
				m.Status = MaterialFailed
			}
			s.mu.Unlock()
			s.log("error", "material "+id+" processing failed: no material processor configured")
			return
		}

		s.mu.RLock()
		m, ok := s.materials[id]
		s.mu.RUnlock()
		if !ok {
			return
		}

		ctx, cancel := context.WithTimeout(context.Background(), materialProcessingTimeout)
		defer cancel()
		processed, err := processor.Process(ctx, m)

		s.mu.Lock()
		cur, ok := s.materials[id]
		if !ok {
			s.mu.Unlock()
			return
		}
		if err != nil {
			cur.Status = MaterialFailed
			cur.RAGAvailable = false
			s.mu.Unlock()
			s.log("error", "material "+id+" processing failed: "+err.Error())
			return
		}

		chunks := make([]MaterialChunk, len(processed))
		for i, p := range processed {
			chunks[i] = MaterialChunk{ID: NewID("chk"), MaterialID: id, Text: p.Text, Embedding: p.Embedding}
		}
		s.chunks[id] = chunks
		cur.Status = MaterialReady
		cur.RAGAvailable = len(chunks) > 0
		s.mu.Unlock()

		s.log("info", "material "+id+" processed successfully into "+strconv.Itoa(len(chunks))+" chunk(s)")
	}()
}

// ListMaterials returns all materials, most recently uploaded first.
func (s *Store) ListMaterials() []*Material {
	s.mu.RLock()
	defer s.mu.RUnlock()

	out := make([]*Material, 0, len(s.materials))
	for _, m := range s.materials {
		out = append(out, m)
	}
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j].UploadedAt.After(out[j-1].UploadedAt); j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}

// GetMaterial looks up a material by ID.
func (s *Store) GetMaterial(id string) (*Material, error) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	m, ok := s.materials[id]
	if !ok {
		return nil, ErrNotFound
	}
	return m, nil
}

// MaterialChunks returns the embedded chunks stored for a ready material.
func (s *Store) MaterialChunks(materialID string) []MaterialChunk {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.chunks[materialID]
}

// UpdateMaterialDestination changes where a material's content is routed.
// Callers must validate the path first (see storage.ValidateDestinationPath).
func (s *Store) UpdateMaterialDestination(id, destinationPath string) (*Material, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	m, ok := s.materials[id]
	if !ok {
		return nil, ErrNotFound
	}
	m.DestinationPath = destinationPath
	return m, nil
}

// DeleteMaterial removes a material's record and returns it so the caller
// can clean up its on-disk file.
func (s *Store) DeleteMaterial(id string) (*Material, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	m, ok := s.materials[id]
	if !ok {
		return nil, ErrNotFound
	}
	delete(s.materials, id)
	delete(s.chunks, id)
	return m, nil
}

// ReprocessMaterial resets a material to "processing" and restarts the
// pipeline.
func (s *Store) ReprocessMaterial(id string) (*Material, error) {
	s.mu.Lock()
	m, ok := s.materials[id]
	if !ok {
		s.mu.Unlock()
		return nil, ErrNotFound
	}
	m.Status = MaterialProcessing
	m.RAGAvailable = false
	delete(s.chunks, id)
	s.mu.Unlock()

	s.startProcessing(id)
	return m, nil
}
